FROM python:3.9-slim

# 1. Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# 2. Install Python packages
WORKDIR /app
ENV PYTHONPATH="/app"
COPY ../requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# 3. Copy app and run
COPY . .
CMD ["python", "consumer/main.py"]